version: '3'
services:
  nodered:
    build: .
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YourPass
      MYSQL_DATABASE: Node-DB
      MYSQL_USER: YourUser
      MYSQL_PASSWORD: YouPass
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
